### ISSUE TITLE
token 和 cookie 获取

### ISSUE THREAD

**Issue by flashclub** [ZejunCao/WeChatOA_Aggregation#1]
作者你好，感谢你贡献了这个项目
提示 invalid session 过期了。请问是在浏览器中打开公众号文章获取cookie后粘贴吗？
我这样试了依然不行，浏览器中得到的cookie内容没有你示例中的全

**Comment by flashclub** [comment]
> 作者你好，感谢你贡献了这个项目 提示 invalid session 过期了。请问是在浏览器中打开公众号文章获取cookie后粘贴吗？ 我这样试了依然不行，浏览器中得到的cookie内容没有你示例中的全

这个问题解决了哈。
另外一个问题是只能读到一个公众号的近20条文章，如何获取到历史上全部文章呢

**Comment by ZejunCao** [comment]
> 这个问题解决了哈。 另外一个问题是只能读到一个公众号的近20条文章，如何获取到历史上全部文章呢

修改fakeid2message_update函数（wechat_request.py）的params参数中的begin和count字段，可以把count设置的很大，也可以循环获取，例如begin=20、count=20，再下次begin=40、count=20

**Comment by flashclub** [comment]
> > 这个问题解决了哈。 另外一个问题是只能读到一个公众号的近20条文章，如何获取到历史上全部文章呢
> 
> 修改fakeid2message_update函数（wechat_request.py）的params参数中的begin和count字段，可以把count设置的很大，也可以循环获取，例如begin=20、count=20，再下次begin=40、count=20

好的感谢，试了下，count放大没起作用还是每次返回20个，不知道为啥。修改了begin可以用了继续下了

**Comment by ZejunCao** [comment]
> 好的感谢，试了下，count放大没起作用还是每次返回20个，不知道为啥。修改了begin可以用了继续下了

好的，好用的话给个star哦，后续会及时更新文章筛选及模拟登陆的

**Comment by flashclub** [comment]
好的 star了
