### ISSUE TITLE
id_info.json的内容如何获取

### ISSUE THREAD

**Issue by CodinShark** [ZejunCao/WeChatOA_Aggregation#2]
您好，想请教id_info.json文件内容是如何得到的。

**Comment by ZejunCao** [comment]
进入微信公众平台，新建图文内容，引入超链接，按F12打开network，随便输入一个公众号名字，平台会自动抓包，点开请求的包就能找到token和cookie。
后续全部开发完会整理成博客和视频，觉得有用的话给个star或者fork一下哦

**Comment by himcrh** [comment]
能否再详细一点，我找到的cookie头都是pgv_pvid，token并没有找到。我使用的是公众平台新建图文的引用功能

**Comment by jooooock** [comment]
也可以参考 https://github.com/jooooock/wechat-article-exporter/blob/master/pages/login.vue 实现扫码登录，这样更方便一点

**Comment by ZejunCao** [comment]
> 也可以参考 https://github.com/jooooock/wechat-article-exporter/blob/master/pages/login.vue 实现扫码登录，这样更方便一点

好的，我参考优化一下，谢谢
