### ISSUE TITLE
根据公众号名称获取 fakeid, 即 _biz 的接口失效

### ISSUE THREAD

**Issue by ChaXxl** [ZejunCao/WeChatOA_Aggregation#5]
如图：
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/be26307c-0ca4-4b23-a4fd-301441c14927">

**Comment by ZejunCao** [comment]
这个我试了下，用postman这种工具确实会出现这种情况，但是直接复制拼接参数的地址：https://mp.weixin.qq.com/cgi-bin/searchbiz?action=search_biz&begin=0&count=5&query=%E8%80%81%E5%88%98%E8%AF%B4NLP&token=1012532014&lang=zh_CN&f=json&ajax=1
放到浏览器中可以得到，用python函数也可以得到，具体原因未知
<img width="718" alt="Snipaste_2024-09-10_23-21-26" src="https://github.com/user-attachments/assets/c63aef19-4966-4083-8a26-f864affec7af">

**Comment by ChaXxl** [comment]
在请求头里面需要带上 Cookie 才能拿到数据，看来代码得更新了
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/7d39e724-dbc2-451d-9af0-079655855d1c">

**Comment by ZejunCao** [comment]
又测了测，确实是这样，晚上更新一下

**Comment by ChaXxl** [comment]
fix: #6
